### ISSUE TITLE
../Adafruit_GFX/Adafruit_GFX.h: No such file or directory

### ISSUE THREAD

**Issue by toddmedema** [delianides/SparkCore-NeoMatrix#1]
Veryfing code using this library in Particle Build fails with this error:

```
neomatrix/neomatrix.h:24:42: fatal error: ../Adafruit_GFX/Adafruit_GFX.h: No such file or directory
 #include "../Adafruit_GFX/Adafruit_GFX.h"
                                          ^
```

My code:

```
#include "neomatrix/neomatrix.h"

Adafruit_NeoMatrix matrix = Adafruit_NeoMatrix(8,8,4,1, PIXEL_PIN,
  NEO_TILE_TOP   + NEO_TILE_LEFT   + NEO_TILE_ROWS   + NEO_TILE_PROGRESSIVE +
  NEO_MATRIX_TOP + NEO_MATRIX_LEFT + NEO_MATRIX_ROWS + NEO_MATRIX_PROGRESSIVE,
  PIXEL_TYPE);

const uint16_t colors[] = {
  matrix.Color(255, 0, 0), matrix.Color(0, 255, 0), matrix.Color(0, 0, 255) };

void setup() {
  matrix.begin();
  matrix.setTextWrap(false);
  matrix.setBrightness(30);
  matrix.setTextColor(matrix.Color(80,255,0));
}

int x    = matrix.width();
int pass = 0;

void loop() {
  matrix.fillScreen(0);
  matrix.setCursor(x, 0);
  matrix.print(F("Happy Birthday William"));
  if(--x < -36) {
    x = matrix.width();
    if(++pass >= 3) pass = 0;
    matrix.setTextColor(colors[pass]);
  }
  matrix.show();
  delay(100);
}
```

**Comment by delianides** [comment]
Did you include the `Adafruit_GFX` library in your project too?

**Comment by toddmedema** [comment]
Ah! There we go...Though, now it's still not showing anything on the matrix, and I've confirmed that my level shifter is properly boosting the 3.3v logic to 5v (by setting the output pin to high and confirming that the level shifted output is 5v).

Any thoughts on other things I could check to debug? Sad that getting the LED matrix running is nowhere near as fast / easy as hoped :( (but thank you for the fast response!)

**Comment by delianides** [comment]
What did you set for `PIXEL_TYPE`? If you've purchased your matrices recently then replace `PIXEL_TYPE` with `NEO_KHZ800` but I think you can leave it off completely and the library uses the common (correct) type as a default. I've been using this which has been working:

```
//Define Matrix
Adafruit_NeoMatrix matrix = Adafruit_NeoMatrix(8,8,5,1, PIXEL_PIN,
  NEO_TILE_TOP   + NEO_TILE_LEFT   + NEO_TILE_ROWS   + NEO_TILE_PROGRESSIVE +
  NEO_MATRIX_TOP + NEO_MATRIX_LEFT + NEO_MATRIX_ROWS + NEO_MATRIX_PROGRESSIVE
);
```

**Comment by delianides** [comment]
@toddmedema did you find a solution?

**Comment by toddmedema** [comment]
Thanks for following up - haven't had a chance to get back to this project, but will let you know when I do / if it works!

**Comment by llynyrd** [comment]
The same issue is happening to me didn't see this before I opened a new issue. Thought it was caused my particle auto adding the libraries at the top but even when I make those into comments I get the same error as you. @toddmedema did you ever find a solution?
