### ISSUE TITLE
GFX & NeoPixel library includes broken

### ISSUE THREAD

**Issue by degrande107** [delianides/SparkCore-NeoMatrix#5]
Since the new library 2.0 system came out for the Particle Web IDE, any project that includes this library cannot compile.

Long story short, the GFX & NeoPixel library includes should be changed as follows:

`#include "../Adafruit_GFX/Adafruit_GFX.h"`
`#include "../neopixel/neopixel.h"`

to 

`#include "Adafruit_GFX.h"`
`#include "neopixel.h"`

Discussion of this in Particle Community: [https://community.particle.io/t/neomatrix-library-web-ide-issue/33123/2](url)

**Comment by delianides** [comment]
@degrande107 I'll take a look this weekend and test out this change to make sure it works.

**Comment by delianides** [comment]
@degrande107 I've published the an update to the library that includes the changes you've mentioned as well as auto include Adafruit_GFX and neopixel libraries. The new version is 0.2.0.

Thanks!
