### ISSUE TITLE
Please reupload and publish the updated version

### ISSUE THREAD

**Issue by ScruffR** [delianides/SparkCore-NeoMatrix#8]
@delianides, two months ago you obviously updated the `neopixel` dependency to v1.0.0 but the Particle Library repository still holds the version that depends on 0.0.14.

Can you please reupload and publish the updated version?

The required commands ...
```
particle library upload
particle library publish
```
... should be executed from the location of the `library.properties` file of that library.

Thanks

**Comment by delianides** [comment]
@ScruffR this is resolved now. Published version 0.3
